site_name: Community Biology Biosafety Handbook
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
  - Welcome: index.md
  - Chapter 1: Chapter 1.md
  - Chapter 2: Chapter 2.md
  - Chapter 3: Chapter 3.md
  - Chapter 4: Chapter 4.md
  - Chapter 5: Chapter 5.md
  - Chapter 6: Chapter 6.md
  - Chapter 7: Chapter 7.md
  - Chapter 8: Chapter 8.md
  - Chapter 9: Chapter 9.md
  - Chapter 10: Chapter 10.md
  - Chapter 11: Chapter 11.md
  - Chapter 12: Chapter 12.md
  - Chapter 13: Chapter 13.md
  - Chapter 14: Chapter 14.md
  - Chapter 15: Chapter 15.md
  - Chapter 16: Chapter 16.md
  - Chapter 17: Chapter 17.md

