site_name: Community Biology Biosafety Handbook
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
  - 'Welcome.md'
  - Chapter 1: Chapter 1.md
  - Chapter 2: Chapter 2.md
  - Chapter 3: Chapter 3.md
  - Chapter 4: Chapter 4.md